sudo: false
language: node_js
node_js:
  - 'lts/*'
  - '9'

script:
  - npm run build
  - npm run test
  - npm run eslint

notifications:
  email: false
  irc:
    channels:
      - 'chat.freenode.net#indico'
    use_notice: true
    skip_join: true
